[package]
name = "host_register"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.173", features = ["derive"] }
serde_json = "1.0.103"
nanoid = "0.4.0"
enet = "0.3.0"